import Head from 'next/head';
import { useTranslation } from 'react-i18next';
import { useEffect, useState } from 'react';
import Hero from '../components/Home/Hero';
import Client from '../components/Home/Client';
import Portfolio from '../components/Home/Portfolio';
import Feature from '../components/Home/Feature';
import VR from '../components/Home/VR';
import Benefit from '../components/Home/Benefit';
import CTA from '../components/partials/CTA';
import Header from '../components/partials/Header';
import Footer from '../components/partials/Footer';

import BacktoTopButton from '../components/partials/BacktoTopButton';

import {
  clientsData,
  portfolioData,
  featuresData,
  virtualRealityData,
  benefitsData,
  benefitButtonsData,
  ctaData,
} from './api/data/id/HomeData';

import {
  clientsDataEn,
  portfolioDataEn,
  featuresDataEn,
  virtualRealityDataEn,
  benefitsDataEn,
  benefitButtonsDataEn,
  ctaDataEn,
} from './api/data/en/HomeData';

import { AppContext } from '../context/app-context';

export default function Home() {
  const { t, i18n } = useTranslation();

  let lang;
  useEffect(() => {
    if (localStorage.language === 'en') {
      lang = 'en';
    } else {
      lang = 'id';
    }
  });

  const [language, setLanguage] = useState(lang);

  const onClickLanguageHandler = () => {
    const toggleLanguage = document.querySelector('#toggleLanguage');
    if (toggleLanguage.checked) {
      localStorage.language = 'id';
      i18n.changeLanguage('id');
      setLanguage('id');
    } else {
      localStorage.language = 'en';
      i18n.changeLanguage('en');
      setLanguage('en');
    }
  };

  let clients;
  let portfolios;
  let features;
  let virtualReality;
  let benefits;
  let benefitButtons;
  let cta;

  if (language === 'id') {
    clients = clientsData();
    portfolios = portfolioData();
    features = featuresData();
    virtualReality = virtualRealityData();
    benefits = benefitsData();
    benefitButtons = benefitButtonsData();
    cta = ctaData();
  } else {
    clients = clientsDataEn();
    portfolios = portfolioDataEn();
    features = featuresDataEn();
    virtualReality = virtualRealityDataEn();
    benefits = benefitsDataEn();
    benefitButtons = benefitButtonsDataEn();
    cta = ctaDataEn();
  }

  const appContextValue = {
    clients,
    portfolios,
    features,
    virtualReality,
    benefits,
    benefitButtons,
  };

  return (
    <>
      <Head>
        <title>
          Virtual Reality Digidaxa - Make Good Visualization Your Bussiness with Virtual Reality
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <a href="#content" className="skip-link focus:top-0 hover:text-light/50">{t('skipButtonText')}</a>

      <Header
        language={language}
        onClickLanguage={onClickLanguageHandler}
      />

      <main id="content">
        <Hero />
        <AppContext.Provider value={appContextValue}>
          <Client />
          <Portfolio />
          <Feature />
          <VR />
          <Benefit />
        </AppContext.Provider>
        <CTA cta={cta} />
      </main>

      <BacktoTopButton />
      <Footer language={language} />
    </>
  );
}
