import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import Head from 'next/head';
import Hero from '../components/Home/Hero';
import Client from '../components/Home/Client';
import Portfolio from '../components/Home/Portfolio';
import Feature from '../components/Home/Feature';
import VR from '../components/Home/VR';
import Benefit from '../components/Home/Benefit';
import CTA from '../components/Partials/CTA';

import {
  clientsData,
  portfolioData,
  featuresData,
  virtualRealityData,
  benefitsData,
  benefitButtonsData,
  ctaData,
} from './api/data/id/HomeData';

import {
  clientsDataEn,
  portfolioDataEn,
  featuresDataEn,
  virtualRealityDataEn,
  benefitsDataEn,
  benefitButtonsDataEn,
  ctaDataEn,
} from './api/data/en/HomeData';

import { AppContext } from '../context/app-context';

export default function Home({ language }) {
  let clients;
  let portfolios;
  let features;
  let virtualReality;
  let benefits;
  let benefitButtons;
  let cta;

  if (language === 'id') {
    clients = clientsData();
    portfolios = portfolioData();
    features = featuresData();
    virtualReality = virtualRealityData();
    benefits = benefitsData();
    benefitButtons = benefitButtonsData();
    cta = ctaData();
  } else {
    clients = clientsDataEn();
    portfolios = portfolioDataEn();
    features = featuresDataEn();
    virtualReality = virtualRealityDataEn();
    benefits = benefitsDataEn();
    benefitButtons = benefitButtonsDataEn();
    cta = ctaDataEn();
  }

  const appContextValue = {
    clients,
    portfolios,
    features,
    virtualReality,
    benefits,
    benefitButtons,
  };

  return (
    <>
      <Head>
        <title>
          Virtual Reality Digidaxa - Make Good Visualization Your Bussiness with Virtual Reality
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="content">
        <Hero />
        <AppContext.Provider value={appContextValue}>
          <Client />
          <Portfolio />
          <Feature />
          <VR />
          <Benefit />
        </AppContext.Provider>
        <CTA cta={cta} />
      </main>

    </>
  );
}

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common', 'home'])),
  },
});
